# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Libelle', models.CharField(default='Categorie_No_Name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ordre', models.IntegerField()),
                ('Montant', models.FloatField()),
                ('Valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(blank=True, max_length=250, null=True)),
                ('Date_Notif', models.DateTimeField(default=django.utils.timezone.now)),
                ('Vue', models.BooleanField(default=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(default='Produit_No_Name', max_length=10)),
                ('Prix', models.FloatField(blank=True, default=None, null=True)),
                ('Categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telephone', models.IntegerField(null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='Client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='Produits',
            field=models.ManyToManyField(to='app.Produit'),
        ),
    ]
