# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Commande'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='Categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='Designation',
            field=models.CharField(default='Produit_No_Name', max_length=30),
        ),
    ]
